runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /.*
  script: main.app

# [START handle_incoming_email]
#- url: /_ah/mail/.+
#  script: handle_incoming_email.app
#  login: admin
# [END handle_incoming_email]
